services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_DATABASE: wp
    volumes:
      - db_data:/var/lib/mysql

  wp:
    build: ./tools/docker/wordpress
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    environment:
      SMTPSERVER: mailhog
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_USER: wp
      PMA_PASSWORD: wp
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8085:8025

volumes:
  db_data:
