# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Test

on:
  push:

jobs:

  test:
    # https://github.com/actions/runner-images/blob/27d8a9d9026ab6e207340dde6e14f4faf3864e29/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Make project root directory writable by Docker user
        run: docker compose run --remove-orphans wp chown -R www-data /var/www/html

      - name: Install dependencies
        run: npm run cli -- composer install

      - name: Start the environment
        run: npm run start

      - name: Setup WordPress
        run: npm run wp -- core install

        # TODO: replace with an actual test
      - name: List plugins
        run: npm run wp -- plugin list 
